'use client'
import{useEffect,useRef,useState}from'react'
import{NEWHAM_BOUNDS}from'../lib/newhamSeedData'
const GREEN='#078d16',BLUE='#0b73d9',GREY='#9d9da5',PURPLE='#8E44AD',ORANGE='#ff681f'
function loadGoogleMaps(apiKey){return new Promise((resolve,reject)=>{if(typeof window==='undefined')return reject(new Error('No window'));if(window.google?.maps)return resolve(window.google.maps);const existing=document.getElementById('gmaps-script');if(existing){existing.addEventListener('load',()=>resolve(window.google.maps),{once:true});existing.addEventListener('error',()=>reject(new Error('Failed to load Google Maps script')),{once:true});return}const script=document.createElement('script');script.id='gmaps-script';script.src=`https://maps.googleapis.com/maps/api/js?key=${apiKey}&libraries=places`;script.async=true;script.defer=true;script.onload=()=>resolve(window.google.maps);script.onerror=()=>reject(new Error('Failed to load Google Maps script'));document.head.appendChild(script)})}
function controlledNow(){const d=new Date(),m=d.getHours()*60+d.getMinutes();return m>=8*60&&m<18*60+30}
function point(seg){if(seg.lat&&seg.lng)return{lat:seg.lat,lng:seg.lng};const coords=seg.coords||[];const mid=coords[Math.floor(coords.length/2)]||coords[0];return mid?{lat:mid[0],lng:mid[1]}:null}
function visual(seg){if(seg.isCarPark||seg.type==='carpark')return{color:BLUE,label:'P'};if(['restricted','no_parking','yellow_double','red_route'].includes(seg.type))return{color:GREY,label:'X'};if(seg.type==='paid')return{color:controlledNow()?BLUE:GREEN,label:controlledNow()?'£':'P'};if(seg.type==='disabled')return{color:PURPLE,label:'BB'};if(seg.type==='ev')return{color:'#29c9b2',label:'EV'};if(seg.type==='loading')return{color:ORANGE,label:'L'};return{color:GREEN,label:'P'}}
function pathFromCoords(coords){return(coords||[]).map(([lat,lng])=>({lat,lng}))}
function snapKey(seg){const coords=seg.coords||[],last=coords[coords.length-1];return`${seg.id}:${coords.length}:${coords[0]?.join(',')||''}:${last?.join(',')||''}`}
function inBounds(p){return p.lat>=NEWHAM_BOUNDS.south&&p.lat<=NEWHAM_BOUNDS.north&&p.lng>=NEWHAM_BOUNDS.west&&p.lng<=NEWHAM_BOUNDS.east}
function markerScale(label){return label.length>1?14:15}
export default function GoogleMap({apiKey,center,zoom=15,segments=[],offers=[],places=[],onSegmentClick,onOfferClick,onMapMove,onGoogleParking}){
  const containerRef=useRef(null),mapRef=useRef(null),overlaysRef=useRef([]),placesServiceRef=useRef(null),googleParkingRef=useRef([]),userMarkerRef=useRef(null),snapCacheRef=useRef(new Map())
  const[mapReady,setMapReady]=useState(false)
  const[snappedPaths,setSnappedPaths]=useState({})
  useEffect(()=>{if(!apiKey||!containerRef.current||mapRef.current)return;loadGoogleMaps(apiKey).then((maps)=>{const map=new maps.Map(containerRef.current,{center,zoom,mapTypeControl:false,streetViewControl:false,fullscreenControl:false,clickableIcons:true,gestureHandling:'greedy',restriction:{latLngBounds:NEWHAM_BOUNDS,strictBounds:false},styles:[{featureType:'poi.business',stylers:[{visibility:'on'}]},{featureType:'poi.park',elementType:'geometry',stylers:[{color:'#dff2df'}]},{featureType:'road',elementType:'geometry',stylers:[{color:'#ffffff'}]},{featureType:'road',elementType:'labels.text.fill',stylers:[{color:'#5e5b6f'}]},{featureType:'landscape',stylers:[{color:'#efeee9'}]}]});mapRef.current=map;placesServiceRef.current=new maps.places.PlacesService(map);userMarkerRef.current=new maps.Marker({position:center,map,title:'Your location',zIndex:80,icon:{path:maps.SymbolPath.CIRCLE,scale:8,fillColor:'#1475e8',fillOpacity:1,strokeColor:'#ffffff',strokeWeight:3}});map.addListener('idle',()=>{const b=map.getBounds();if(!b)return;const ne=b.getNorthEast(),sw=b.getSouthWest();onMapMove?.({south:sw.lat(),west:sw.lng(),north:ne.lat(),east:ne.lng()})});setMapReady(true)}).catch(error=>console.error('Google Maps failed to load',error))},[apiKey])
  useEffect(()=>{let cancelled=false;const lineSegments=segments.filter(seg=>Array.isArray(seg.coords)&&seg.coords.length>1).slice(0,120);lineSegments.forEach(seg=>{const key=snapKey(seg);if(snapCacheRef.current.has(key))return;snapCacheRef.current.set(key,null);fetch('/api/parking/snap-road',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({coords:seg.coords,interpolate:true})}).then(r=>r.json()).then(json=>{if(cancelled)return;if(!json?.ok||!Array.isArray(json.coords)||json.coords.length<2){snapCacheRef.current.set(key,false);return}snapCacheRef.current.set(key,json.coords);setSnappedPaths(prev=>({...prev,[seg.id]:json.coords}))}).catch(()=>snapCacheRef.current.set(key,false))});return()=>{cancelled=true}},[segments])
  useEffect(()=>{const map=mapRef.current;if(!mapReady||!map||!window.google?.maps)return;overlaysRef.current.forEach(o=>o.setMap?.(null));overlaysRef.current=[];const maps=window.google.maps;segments.forEach(seg=>{const p=point(seg);if(!p)return;const v=visual(seg);const snapped=snappedPaths[seg.id];if(Array.isArray(snapped)&&snapped.length>1){const linePath=pathFromCoords(snapped);const casing=new maps.Polyline({path:linePath,map,strokeColor:'#ffffff',strokeOpacity:.96,strokeWeight:8,zIndex:30,clickable:false});const line=new maps.Polyline({path:linePath,map,strokeColor:seg.color||v.color,strokeOpacity:.98,strokeWeight:5,zIndex:31,icons:[{icon:{path:maps.SymbolPath.CIRCLE,scale:3,fillColor:seg.color||v.color,fillOpacity:1,strokeColor:'#ffffff',strokeWeight:1},offset:'50%'}]});line.addListener('click',()=>onSegmentClick?.(seg));overlaysRef.current.push(casing,line);return}const marker=new maps.Marker({position:p,map,title:seg.name||'Parking',label:{text:v.label,color:'#ffffff',fontSize:v.label.length>1?'11px':'15px',fontWeight:'900'},zIndex:40,icon:{path:maps.SymbolPath.CIRCLE,scale:markerScale(v.label),fillColor:v.color,fillOpacity:1,strokeColor:'#ffffff',strokeWeight:3}});marker.addListener('click',()=>onSegmentClick?.(seg));overlaysRef.current.push(marker)});places.slice(0,10).forEach(place=>{if(!place.lat||!place.lng)return;const marker=new maps.Marker({position:{lat:place.lat,lng:place.lng},map,title:place.name,zIndex:20,icon:{path:maps.SymbolPath.CIRCLE,scale:5,fillColor:'#ffffff',fillOpacity:1,strokeColor:'#d6d2e5',strokeWeight:2}});overlaysRef.current.push(marker)});offers.forEach(offer=>{if(!offer.lat||!offer.lng)return;const marker=new maps.Marker({position:{lat:offer.lat,lng:offer.lng},map,title:offer.title||offer.businessName||'Offer',label:{text:(offer.shortLabel||offer.discount||'Offer').slice(0,14),color:'#ffffff',fontSize:'11px',fontWeight:'900'},zIndex:70,icon:{path:maps.SymbolPath.BACKWARD_CLOSED_ARROW,scale:8,fillColor:'#ff681f',fillOpacity:1,strokeColor:'#ffffff',strokeWeight:2}});marker.addListener('click',()=>onOfferClick?.(offer));overlaysRef.current.push(marker)})},[mapReady,segments,offers,places,onSegmentClick,onOfferClick,snappedPaths])
  useEffect(()=>{const map=mapRef.current,svc=placesServiceRef.current;if(!mapReady||!map||!svc||!window.google?.maps)return;googleParkingRef.current.forEach(m=>m.setMap(null));googleParkingRef.current=[];let live=true;svc.nearbySearch({location:center,radius:1400,type:'parking'},(results,status)=>{if(!live)return;const found=[];if(status!==window.google.maps.places.PlacesServiceStatus.OK||!results){onGoogleParking?.([]);return}results.slice(0,24).forEach(p=>{const loc=p.geometry?.location;if(!loc)return;const lat=loc.lat(),lng=loc.lng();if(!inBounds({lat,lng}))return;const seg={id:'google-parking-'+p.place_id,type:'carpark',isCarPark:true,color:BLUE,lat,lng,coords:[[lat,lng]],name:p.name||'Parking',restriction:'Parking place from Google. Check signs and operator rules.',hours:p.opening_hours?.open_now?'Open now':'Check opening times',maxStay:null,googlePlaceId:p.place_id,address:p.vicinity||'',source:'google',sourceName:'Google Places',confidence:'medium',dataNote:'Google parking place result. Prices and street restrictions still need signs or operator confirmation.'};found.push(seg);const marker=new window.google.maps.Marker({position:{lat,lng},map,title:seg.name,label:{text:'P',color:'#fff',fontSize:'15px',fontWeight:'900'},zIndex:60,icon:{path:window.google.maps.SymbolPath.CIRCLE,scale:16,fillColor:BLUE,fillOpacity:1,strokeColor:'#fff',strokeWeight:3}});marker.addListener('click',()=>onSegmentClick?.(seg));googleParkingRef.current.push(marker)});onGoogleParking?.(found)});return()=>{live=false}},[mapReady,center.lat,center.lng,onSegmentClick,onGoogleParking])
  useEffect(()=>{const map=mapRef.current;if(!map)return;map.setCenter(center);map.setZoom(zoom);userMarkerRef.current?.setPosition(center)},[center,zoom])
  return <div ref={containerRef} style={{position:'absolute',inset:0,width:'100%',height:'100%'}}/>
}
