'use client'
import{useEffect,useRef}from'react'
import{NEWHAM_BOUNDS}from'../lib/newhamSeedData'
const MAP_STYLE_URL='https://basemaps.cartocdn.com/gl/positron-gl-style/style.json'
const GREEN='#078d16',BLUE='#0b73d9',GREY='#9d9da5',PURPLE='#8E44AD',ORANGE='#ff681f'
function visual(seg){if(seg.type==='disabled')return{color:PURPLE,label:'BB'};if(seg.isCarPark||seg.type==='carpark')return{color:BLUE,label:'P'};if(['restricted','no_parking','yellow_double','red_route'].includes(seg.type))return{color:GREY,label:'X'};if(seg.type==='loading')return{color:ORANGE,label:'L'};return{color:GREEN,label:'P'}}
function point(seg){const p=seg.coords?.[Math.floor((seg.coords?.length||1)/2)]||seg.coords?.[0];return{lat:seg.lat||p?.[0],lng:seg.lng||p?.[1]}}
function drawAsLine(seg){return Array.isArray(seg.coords)&&seg.coords.length>1&&(['dtro','council','curated','field_checked','osm','verified_blue_badge','surveyed_blue_badge'].includes(seg.source)||seg.confidence==='high')}
function lineFeatures(segments){return{type:'FeatureCollection',features:(segments||[]).filter(drawAsLine).map(seg=>{const v=visual(seg);return{type:'Feature',properties:{id:String(seg.id),color:seg.color||v.color,label:v.label,type:seg.type||'disabled',source:seg.source||''},geometry:{type:'LineString',coordinates:seg.coords.map(([lat,lng])=>[lng,lat])}}})}}
function property(properties,names,fallback=''){for(const name of names){if(properties?.[name]!==undefined&&properties?.[name]!==null&&String(properties[name]).trim())return String(properties[name]).trim()}return fallback}
function cpzSegment(feature){const p=feature.properties||{},zone=property(p,['zone','Zone','ZONE','CPZ','Name','NAME','OBJECTID'],'Newham CPZ');return{id:`cpz-${feature.id||zone}`,type:'resident',color:GREEN,coords:[],lat:null,lng:null,name:`${zone} Controlled Parking Zone`,restriction:'CPZ background only. Blue Badge bay locations are shown separately in purple when verified or surveyed.',hours:property(p,['Hours','hours','OPERATING_HOURS','OperatingHours','TIMES','Times'],'Check Newham CPZ operating-hours table'),maxStay:null,cpz:zone,isCarPark:false,source:'newham_cpz',sourceName:'Newham Council ArcGIS CPZ',confidence:'high',dataNote:'Official Newham CPZ polygon from Newham ArcGIS. This is background context, not a Blue Badge bay.'}}
function addCpzLayer(map,onSegmentClick){fetch('/api/newham/cpz').then(r=>r.json()).then(data=>{if(!map||map.getSource('newham-cpz'))return;const geo=data?.features?.length?data:{type:'FeatureCollection',features:[]};map.addSource('newham-cpz',{type:'geojson',data:geo});map.addLayer({id:'newham-cpz-fill',type:'fill',source:'newham-cpz',paint:{'fill-color':'#8E44AD','fill-opacity':['case',['boolean',['feature-state','hover'],false],.12,.045]}});map.addLayer({id:'newham-cpz-line',type:'line',source:'newham-cpz',paint:{'line-color':'#8E44AD','line-width':['interpolate',['linear'],['zoom'],10,.7,15,1.5,19,2.5],'line-opacity':.38}});map.addLayer({id:'newham-cpz-labels',type:'symbol',source:'newham-cpz',minzoom:12,layout:{'text-field':['coalesce',['get','zone'],['get','Zone'],['get','ZONE'],['get','CPZ'],['get','Name'],['get','NAME'],'CPZ'],'text-size':['interpolate',['linear'],['zoom'],12,10,16,13],'text-font':['Open Sans Bold'],'text-allow-overlap':false},paint:{'text-color':'#6b328f','text-halo-color':'#ffffff','text-halo-width':2}});map.on('click','newham-cpz-fill',e=>{const f=e.features?.[0];if(f)onSegmentClick?.(cpzSegment(f))});map.on('mouseenter','newham-cpz-fill',()=>{map.getCanvas().style.cursor='pointer'});map.on('mouseleave','newham-cpz-fill',()=>{map.getCanvas().style.cursor='grab'})}).catch(()=>{})}
function upsertParkingLines(map,segments){const data=lineFeatures(segments);const source=map.getSource('parking-lines');if(source){source.setData(data);return}map.addSource('parking-lines',{type:'geojson',data});map.addLayer({id:'parking-lines-casing',type:'line',source:'parking-lines',paint:{'line-color':'#ffffff','line-width':['interpolate',['linear'],['zoom'],12,5,16,8,19,10],'line-opacity':.98},layout:{'line-cap':'round','line-join':'round'}});map.addLayer({id:'parking-lines',type:'line',source:'parking-lines',paint:{'line-color':['get','color'],'line-width':['interpolate',['linear'],['zoom'],12,3,16,5,19,7],'line-opacity':.98},layout:{'line-cap':'round','line-join':'round'}});map.addLayer({id:'parking-line-labels',type:'symbol',source:'parking-lines',minzoom:15,layout:{'symbol-placement':'line-center','text-field':['get','label'],'text-size':['interpolate',['linear'],['zoom'],15,11,19,13],'text-allow-overlap':true,'text-ignore-placement':true,'text-rotation-alignment':'map','text-keep-upright':true},paint:{'text-color':'#ffffff','text-halo-color':['get','color'],'text-halo-width':8,'text-halo-blur':.5}});map.addLayer({id:'parking-lines-hit',type:'line',source:'parking-lines',paint:{'line-color':'#000','line-width':['interpolate',['linear'],['zoom'],12,18,16,24,19,30],'line-opacity':0},layout:{'line-cap':'round','line-join':'round'}})}
export default function MapLibreMap({center,zoom=15,segments=[],offers=[],places=[],onSegmentClick,onOfferClick,onMapMove}){
  const containerRef=useRef(null),mapRef=useRef(null),parkingMarkersRef=useRef([]),offerMarkersRef=useRef([]),placesRef=useRef([]),userMarkerRef=useRef(null),moveTimerRef=useRef(null),initRef=useRef(false),segmentsRef=useRef([])
  useEffect(()=>{segmentsRef.current=segments},[segments])
  useEffect(()=>{if(initRef.current||!containerRef.current)return;initRef.current=true;import('maplibre-gl').then(({default:ml})=>{const b=NEWHAM_BOUNDS;const maxBounds=[[b.west-.01,b.south-.01],[b.east+.01,b.north+.01]];const map=new ml.Map({container:containerRef.current,style:MAP_STYLE_URL,center:[center.lng,center.lat],zoom,maxZoom:20,minZoom:12,maxBounds,attributionControl:false});map.on('load',()=>{map.fitBounds([[b.west,b.south],[b.east,b.north]],{padding:28,duration:0});addCpzLayer(map,onSegmentClick);upsertParkingLines(map,segmentsRef.current);const el=document.createElement('div');el.className='user-dot';el.innerHTML='<div class="user-dot-pulse"></div><div class="user-dot-inner"></div>';userMarkerRef.current=new ml.Marker({element:el,anchor:'center'}).setLngLat([center.lng,center.lat]).addTo(map);const mb=map.getBounds();onMapMove?.({south:mb.getSouth(),west:mb.getWest(),north:mb.getNorth(),east:mb.getEast()});mapRef.current=map});map.on('click','parking-lines-hit',e=>{const id=e.features?.[0]?.properties?.id;const seg=segmentsRef.current.find(item=>String(item.id)===String(id));if(seg)onSegmentClick?.(seg)});map.on('mouseenter','parking-lines-hit',()=>{map.getCanvas().style.cursor='pointer'});map.on('mouseleave','parking-lines-hit',()=>{map.getCanvas().style.cursor='grab'});map.on('moveend',()=>{clearTimeout(moveTimerRef.current);moveTimerRef.current=setTimeout(()=>{const b=map.getBounds();onMapMove?.({south:b.getSouth(),west:b.getWest(),north:b.getNorth(),east:b.getEast()})},450)})})},[])
  useEffect(()=>{userMarkerRef.current?.setLngLat([center.lng,center.lat])},[center.lat,center.lng])
  const prevC=useRef(null);useEffect(()=>{const map=mapRef.current;if(!map)return;if(prevC.current?.lat===center.lat&&prevC.current?.lng===center.lng)return;prevC.current=center;map.easeTo({center:[center.lng,center.lat],zoom,duration:420})},[center.lat,center.lng,zoom])
  useEffect(()=>{const map=mapRef.current;if(!map)return;if(map.isStyleLoaded())upsertParkingLines(map,segments)},[segments])
  useEffect(()=>{const map=mapRef.current;if(!map)return;parkingMarkersRef.current.forEach(m=>m.remove());parkingMarkersRef.current=[];import('maplibre-gl').then(({default:ml})=>{segments.forEach(seg=>{if(drawAsLine(seg))return;const p=point(seg);if(!p.lat||!p.lng)return;const el=document.createElement('div');el.style.cssText='width:36px;height:36px;border-radius:50%;background:#8E44AD;color:white;border:3px solid white;box-shadow:0 5px 14px rgba(0,0,0,.24);display:flex;align-items:center;justify-content:center;font-weight:900;font-size:12px;cursor:pointer';el.textContent='BB';el.addEventListener('click',()=>onSegmentClick?.(seg));const marker=new ml.Marker({element:el,anchor:'center'}).setLngLat([p.lng,p.lat]).addTo(map);parkingMarkersRef.current.push(marker)})})},[segments,onSegmentClick])
  useEffect(()=>{const map=mapRef.current;if(!map)return;offerMarkersRef.current.forEach(m=>m.remove());offerMarkersRef.current=[];import('maplibre-gl').then(({default:ml})=>{offers.forEach(offer=>{if(!offer.lat||!offer.lng)return;const el=document.createElement('div');el.className='offer-bubble-wrap';el.innerHTML=`<div class="offer-bubble">${offer.shortLabel||offer.title||'Offer'}</div>`;el.addEventListener('click',()=>onOfferClick?.(offer));const marker=new ml.Marker({element:el,anchor:'bottom'}).setLngLat([offer.lng,offer.lat]).addTo(map);offerMarkersRef.current.push(marker)})})},[offers,onOfferClick])
  useEffect(()=>{const map=mapRef.current;if(!map)return;placesRef.current.forEach(m=>m.remove());placesRef.current=[];import('maplibre-gl').then(({default:ml})=>{places.slice(0,14).forEach(place=>{if(!place.lat||!place.lng)return;const el=document.createElement('div');el.className='poi-chip';el.textContent=place.name;el.title=place.category;const marker=new ml.Marker({element:el,anchor:'bottom'}).setLngLat([place.lng,place.lat]).addTo(map);placesRef.current.push(marker)})})},[places])
  return <div ref={containerRef} style={{position:'absolute',inset:0,width:'100%',height:'100%'}}/>
}
