'use client'
import{useEffect,useRef}from'react'
const MAP_STYLE_URL='https://basemaps.cartocdn.com/gl/positron-gl-style/style.json'
const GREEN='#078d16',BLUE='#0b73d9',GREY='#9d9da5',PURPLE='#8E44AD',ORANGE='#ff681f'
function controlledNow(){const d=new Date(),m=d.getHours()*60+d.getMinutes();return m>=8*60&&m<18*60+30}
function visual(seg){if(seg.isCarPark||seg.type==='carpark')return{color:BLUE,label:'P'};if(['restricted','no_parking','yellow_double','red_route'].includes(seg.type))return{color:GREY,label:'⊘'};if(seg.type==='paid')return{color:controlledNow()?BLUE:GREEN,label:controlledNow()?'£':'P'};if(seg.type==='disabled')return{color:PURPLE,label:'♿'};if(seg.type==='ev')return{color:'#29c9b2',label:'⚡'};if(seg.type==='loading')return{color:ORANGE,label:'L'};return{color:GREEN,label:'P'}}
function point(seg){const p=seg.coords?.[Math.floor((seg.coords?.length||1)/2)]||seg.coords?.[0];return{lat:seg.lat||p?.[0],lng:seg.lng||p?.[1]}}
export default function MapLibreMap({center,zoom=15,segments=[],offers=[],places=[],onSegmentClick,onOfferClick,onMapMove}){
  const containerRef=useRef(null),mapRef=useRef(null),parkingMarkersRef=useRef([]),offerMarkersRef=useRef([]),placesRef=useRef([]),userMarkerRef=useRef(null),moveTimerRef=useRef(null),initRef=useRef(false)
  useEffect(()=>{if(initRef.current||!containerRef.current)return;initRef.current=true;import('maplibre-gl').then(({default:ml})=>{const map=new ml.Map({container:containerRef.current,style:MAP_STYLE_URL,center:[center.lng,center.lat],zoom,maxZoom:20,minZoom:5,attributionControl:false});map.on('load',()=>{const el=document.createElement('div');el.className='user-dot';el.innerHTML='<div class="user-dot-pulse"></div><div class="user-dot-inner"></div>';userMarkerRef.current=new ml.Marker({element:el,anchor:'center'}).setLngLat([center.lng,center.lat]).addTo(map);const b=map.getBounds();onMapMove?.({south:b.getSouth(),west:b.getWest(),north:b.getNorth(),east:b.getEast()});mapRef.current=map});map.on('moveend',()=>{clearTimeout(moveTimerRef.current);moveTimerRef.current=setTimeout(()=>{const b=map.getBounds();onMapMove?.({south:b.getSouth(),west:b.getWest(),north:b.getNorth(),east:b.getEast()})},500)})})},[])
  useEffect(()=>{userMarkerRef.current?.setLngLat([center.lng,center.lat])},[center.lat,center.lng])
  const prevC=useRef(null);useEffect(()=>{const map=mapRef.current;if(!map)return;if(prevC.current?.lat===center.lat&&prevC.current?.lng===center.lng)return;prevC.current=center;map.easeTo({center:[center.lng,center.lat],zoom,duration:500})},[center.lat,center.lng,zoom])
  useEffect(()=>{const map=mapRef.current;if(!map)return;parkingMarkersRef.current.forEach(m=>m.remove());parkingMarkersRef.current=[];import('maplibre-gl').then(({default:ml})=>{segments.forEach(seg=>{const p=point(seg);if(!p.lat||!p.lng)return;const v=visual(seg);const el=document.createElement('div');el.style.cssText=`width:34px;height:34px;border-radius:50%;background:${v.color};color:white;border:3px solid white;box-shadow:0 5px 14px rgba(0,0,0,.25);display:flex;align-items:center;justify-content:center;font-weight:900;font-size:15px;cursor:pointer`;el.textContent=v.label;el.addEventListener('click',()=>onSegmentClick?.(seg));const marker=new ml.Marker({element:el,anchor:'center'}).setLngLat([p.lng,p.lat]).addTo(map);parkingMarkersRef.current.push(marker)})})},[segments,onSegmentClick])
  useEffect(()=>{const map=mapRef.current;if(!map)return;offerMarkersRef.current.forEach(m=>m.remove());offerMarkersRef.current=[];import('maplibre-gl').then(({default:ml})=>{offers.forEach(offer=>{if(!offer.lat||!offer.lng)return;const el=document.createElement('div');el.className='offer-bubble-wrap';el.innerHTML=`<div class="offer-bubble">${offer.shortLabel||offer.title||'Offer'}</div>`;el.addEventListener('click',()=>onOfferClick?.(offer));const marker=new ml.Marker({element:el,anchor:'bottom'}).setLngLat([offer.lng,offer.lat]).addTo(map);offerMarkersRef.current.push(marker)})})},[offers,onOfferClick])
  useEffect(()=>{const map=mapRef.current;if(!map)return;placesRef.current.forEach(m=>m.remove());placesRef.current=[];import('maplibre-gl').then(({default:ml})=>{places.slice(0,20).forEach(place=>{if(!place.lat||!place.lng)return;const el=document.createElement('div');el.className='poi-chip';el.textContent=place.name;el.title=place.category;const marker=new ml.Marker({element:el,anchor:'bottom'}).setLngLat([place.lng,place.lat]).addTo(map);placesRef.current.push(marker)})})},[places])
  return <div ref={containerRef} style={{position:'absolute',inset:0,width:'100%',height:'100%'}}/>
}
